apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-svc
  labels:
    app: go-svc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: go-svc
  template:
    metadata:
      labels:
        app: go-svc
    spec:
      serviceAccountName: default
      containers:
        - name: go-svc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8080
          # Standard Go resources for a small API
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"