apiVersion: v1
kind: Service
metadata:
  name: go-svc  # Simple name for internal DNS: http://go-svc:8080
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: 8080        # The port other services use to call this one
      targetPort: 8080  # The actual port the Go app is listening on
      protocol: TCP
  selector:
    app: go-svc         # This MUST match your Deployment labels exactly