replicaCount: 1

image:
  repository: 654654451277.dkr.ecr.ap-south-1.amazonaws.com/node-app
  tag: 2ea8a4b
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

serviceAccount:
  create: true

httpRoute:
  enabled: false

ingress:
  enabled: false
