name: CI-CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION_EKS: ap-southeast-2
  AWS_REGION_ECR: ap-south-1
  ECR_REPOSITORY: node-app
  ECR_GO_REPOSITORY: go-svc
  ECR_FRONTEND_REPOSITORY: frontend
  EKS_CLUSTER_NAME: node-app-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_ECR }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        run: docker buildx create --use

      # ---------- Build NODE IMAGE ----------
      - name: Build and push Node image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            --push services/node-api

      # ---------- Build GO IMAGE ----------
      - name: Build and push Go image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_GO_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            --push services/go-svc

      # ---------- Build FRONTEND IMAGE ----------
      - name: Build and push Frontend image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_FRONTEND_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            --push services/frontend

      # ---------- Connect to EKS ----------
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION_EKS }} \
            --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Setup Helm
        uses: azure/setup-helm@v4

      # ---------- Deploy GO FIRST ----------
      - name: Deploy Go Service
        run: |
          helm upgrade --install go-svc ./charts/go-svc \
            --namespace node-app \
            --create-namespace \
            --set image.repository=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_GO_REPOSITORY }} \
            --set image.tag=${{ env.IMAGE_TAG }}

    # ---------- Deploy FRONTEND ----------
      - name: Deploy Frontend
        run: |
          helm upgrade --install frontend ./charts/frontend \
            --namespace node-app \
            --set image.repository=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_FRONTEND_REPOSITORY }} \
            --set image.tag=${{ env.IMAGE_TAG }}

      # ---------- Deploy NODE ----------
      - name: Deploy Node API
        run: |
          helm upgrade --install node-app ./charts/node-api \
            --namespace node-app \
            --set image.repository=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }} \
            --set image.tag=${{ env.IMAGE_TAG }}

      - name: Verify Rollouts
        run: |
          kubectl rollout status deployment/go-svc -n node-app --timeout=120s
          kubectl rollout status deployment/node-app -n node-app --timeout=120s
          kubectl rollout status deployment/frontend -n node-app --timeout=120s

