name: CI-CD

on:
  push:
    branches:
      - main

# Crucial for the "Commit and Push" step to work
permissions:
  contents: write

env:
  AWS_REGION_EKS: ap-southeast-2
  AWS_REGION_ECR: ap-south-1
  ECR_REPOSITORY: node-app
  ECR_GO_REPOSITORY: go-svc
  ECR_FRONTEND_REPOSITORY: frontend
  EKS_CLUSTER_NAME: node-app-cluster

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_ECR }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        run: docker buildx create --use

      # ---------- Build and Push Images ----------
      - name: Build and push Node image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            --push services/node-api

      - name: Build and push Go image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_GO_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            --push services/go-svc

      - name: Build and push Frontend image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_FRONTEND_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            --push services/frontend

      # ---------- GitOps: Update Helm Values ----------
      - name: Update Image Tags in values.yaml
        run: |
          # sed searches for "tag: " and replaces the rest of the line with the new SHA
          sed -i "s/tag: .*/tag: ${{ env.IMAGE_TAG }}/" charts/node-api/values.yaml
          sed -i "s/tag: .*/tag: ${{ env.IMAGE_TAG }}/" charts/go-svc/values.yaml
          sed -i "s/tag: .*/tag: ${{ env.IMAGE_TAG }}/" charts/frontend/values.yaml

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update image tags to ${{ env.IMAGE_TAG }} [skip ci]"
          file_pattern: 'charts/*/values.yaml'